CREATE DATABASE InsuranceDB;
USE InsuranceDB;

CREATE TABLE IF NOT EXISTS POLICY(
	id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    effectiveDate DATE NOT NULL,
    expiryDate DATE NOT NULL,
    premium DECIMAL(9,2) NOT NULL,
    policyNo VARCHAR(45)
);

CREATE TABLE IF NOT EXISTS TRAVEL(
	policyNo VARCHAR(45)  NOT NULL PRIMARY KEY REFERENCES POLICY(policyNo),
    departure VARCHAR(45) NOT NULL,
    destination VARCHAR(45) NOT NULL,
    family BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS MOTOR(
	policyNo VARCHAR(45)  NOT NULL PRIMARY KEY REFERENCES POLICY(policyNo),
    vehiclePrice DECIMAL(9,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS MEDICAL(
	policyNo VARCHAR(45)  NOT NULL PRIMARY KEY REFERENCES POLICY(policyNo),
	beneficiaries VARCHAR(45) NOT NULL 
);

CREATE TABLE IF NOT EXISTS CLAIM(
	id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	policyNo VARCHAR(45)  NOT NULL REFERENCES POLICY(policyNo),
    amount DECIMAL(9,2) NOT NULL,
    incurred DATE NOT NULL
);

